version: '2'

services:
    openhab:
        build: .
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "run/userdata:/openhab/userdata"
            - "run/conf:/openhab/conf"
        environment:
            OPENHAB_HTTP_PORT: 8080
            OPENHAB_HTTPS_PORT: 18443
        network_mode: "host"
        tty: true
